pipeline{
    agent any
    tools {
          terraform 'my-terraform'
    }
    stages{
        stage("Terraform checking"){
            steps{
                echo "========Start checking Terraform========"
		    dir("jenkins-node") {
			    withCredentials([aws(credentialsId: 'aws-creds')]) { 
                    sh 'terraform --version'
                    sh '''
                        terraform init
                        terraform plan -no-color
			terraform apply
                    '''
		    }
		    }
            }
        }
    }
}
Footer

